apiVersion: broker.amq.io/v2alpha4
kind: ActiveMQArtemis
metadata:
  namespace: bananas
  name: broker
  application: broker
spec:
  acceptors:
    - name: amqp
      port: 5672
      protocols: amqp
      expose: true
  adminPassword: admin
  deploymentPlan:
    size: 1
    persistenceEnabled: false
    requireLogin: false
    messageMigration: false
    managementRBACEnabled: false
    journalType: nio
    jolokiaAgentEnabled: false
    image: placeholder
    storage:
      size: 1Gi
  console:
    expose: true
  adminUser: admin